### ISSUE TITLE
Idea!

### ISSUE THREAD

**Issue by xpyctum** [EvolSoft/ServerChannels#1]
Hm. It's interesting idea... Then player joins, plugin check country by ip adress, if it's not interesting for uoy country, player join in "other" channel, if ip interesting for your country server, player puts in "RU" channel

**Comment by PixelGuy75** [comment]
So if the player has an IP of a certain country, then it will be placed into a channel where other players speak the same language? This would be a good idea.

**Comment by xpyctum** [comment]
Yeah

**Comment by letsplaydev** [comment]
Hey guys :)
 Gar not such a bad idea! We will make our times gone about it.
Yours sincerely lets_play :)

**Comment by xpyctum** [comment]
@letsplaydev :D lol

**Comment by Flavius12** [comment]
Do you mean something like "country" channels?

**Comment by xpyctum** [comment]
@Flavius12 Yeah!

**Comment by Flavius12** [comment]
Interesting, good idea!
Thank you :)

**Comment by xpyctum** [comment]
@Flavius12 :)
I can help you )

**Comment by Praxthisnovcht** [comment]
Woo Nice Idea !

**Comment by Flavius12** [comment]
In v1.3 there will be an advanced API and with an extension this will be possible :)

**Comment by PixelGuy75** [comment]
Awesome
