### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by xpyctum** [EvolSoft/ServerChannels#3]
When player join, he cannot using chat. Only after /sch join staff
Fix?

**Comment by Flavius12** [comment]
Are you sure this bug is related to ServerChannels?

**Comment by xpyctum** [comment]
@Flavius12 yea. I'm remove PureChat and install your plugin. Fix (up comment)

**Comment by Flavius12** [comment]
However I tested chat and I didn't find this bug
