### ISSUE TITLE
I permessi non funzionano!

### ISSUE THREAD

**Issue by matcracker** [EvolSoft/ServerChannels#4]
Ciao! Ho provato a dare tutti i permessi del plugin ai membri dello staff del mio server ma nessuno è in grado di utilizzare i comandi di join/leave eccetto gli OP. Non capisco se è un mio problema oppure no... Perché il plugin PurePerms funziona bene e riscontro questo problema dei permessi solo con questo plugin, al momento. Attendo risposta grazie!

P.s. Spero non sia un problema se ti ho scritto in italiano! :smile:

**Comment by Flavius12** [comment]
Hmm... This is very strange. I'll check the code and I'll do some tests

**Comment by matcracker** [comment]
Have you tried? :)

**Comment by Flavius12** [comment]
Yes
They works correctly on my tests

**Comment by matcracker** [comment]
I gave these two permissions but no one can use them...
- serverchannels.commands.join
- serverchannels.commands.leave
  
  And then I do not understand why in the README file's permission " serverchannels.\* " and " serverchannels.commands.\* " As the file "plugin.yml" is not present "*"

**Comment by Flavius12** [comment]
_\- serverchannels._\* means the parent of all child permissions

However remember that _serverchannels.commands.join_ lets people to use join channel command but you must also give _serverchannels.channels.&lt;channel name&gt;_ to allow people to join the channel

**Comment by matcracker** [comment]
Ohh...! Tomorrow I try and I will tell you! Thanks!

**Comment by Flavius12** [comment]
Ok :+1:
Let me know :)

**Comment by Flavius12** [comment]
Do they work?

**Comment by matcracker** [comment]
No :(

**Comment by matcracker** [comment]
Ho trovato il problema! Ma non è causato da me ma dal plugin! Nel file commands.php hai messo i permessi "serverchannels.channel.<nomecanale>" quando nel plugin.yml sono "serverchannels.channels.<nomecanale>".

Ti ho scritto in italiano perché sono di fretta XD penso non ci siano problemi ;D

**Comment by Flavius12** [comment]
Oops...
Thank you :D

**Comment by Flavius12** [comment]
Fixed in v1.2
